<?php

/**
 * sfMaterializedPath_TestNodeMultipleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfMaterializedPath_TestNodeMultipleTable extends PluginsfMaterializedPath_TestNodeMultipleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfMaterializedPath_TestNodeMultipleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfMaterializedPath_TestNodeMultiple');
    }
}