<?php

/**
 * sfMaterializedPath_TestNodeSingleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfMaterializedPath_TestNodeSingleTable extends PluginsfMaterializedPath_TestNodeSingleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfMaterializedPath_TestNodeSingleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfMaterializedPath_TestNodeSingle');
    }
}