<?php

/**
 * PluginsfMaterializedPath_TestNodeSingleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfMaterializedPath_TestNodeSingleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfMaterializedPath_TestNodeSingleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfMaterializedPath_TestNodeSingle');
    }
}