<?php

/**
 * PluginsfMaterializedPath_TestNodeMultiple
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    acts_as_materialized_path
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfMaterializedPath_TestNodeMultiple extends BasesfMaterializedPath_TestNodeMultiple
{
}
