<?php

/**
 * PluginsfMaterializedPath_TestNodeMultipleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfMaterializedPath_TestNodeMultipleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfMaterializedPath_TestNodeMultipleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfMaterializedPath_TestNodeMultiple');
    }
}